//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mkwsb.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mkwsb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Shares the host&apos;s microphone input into the sandbox. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioInput {
            get {
                return ResourceManager.GetString("AudioInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shares the host clipboard with the sandbox so that text and files can be pasted back and forth. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClipboardRedirection {
            get {
                return ResourceManager.GetString("ClipboardRedirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A command to execute when Windows Sandbox starts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogonCommand {
            get {
                return ResourceManager.GetString("LogonCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share folders from the host with read or write permissions.
        ///Exposing host directories might allow malicious software to affect the system or steal data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MappedFolders {
            get {
                return ResourceManager.GetString("MappedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The amount of memory, in megabytes, to assign to the sandbox. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MemoryInMB {
            get {
                return ResourceManager.GetString("MemoryInMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable or disable network access within the sandbox. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Networking {
            get {
                return ResourceManager.GetString("Networking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shares printers from the host into the sandbox. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrinterRedirection {
            get {
                return ResourceManager.GetString("PrinterRedirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Places increased security settings on the Remote Desktop Protocol (RDP) session to the sandbox. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProtectedClient {
            get {
                return ResourceManager.GetString("ProtectedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable or disable the virtualized GPU.
        ///If vGPU is disabled, the sandbox uses Windows Advanced Rasterization Platform (WARP). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string vGPU {
            get {
                return ResourceManager.GetString("vGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shares the host&apos;s webcam input into the sandbox. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VideoInput {
            get {
                return ResourceManager.GetString("VideoInput", resourceCulture);
            }
        }
    }
}
